name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [esp32dev, nodemcuv2]

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO tests
      run: pio test -e ${{ matrix.board }}

    - name: Build examples
      run: |
        pio ci --lib="." --board=${{ matrix.board }} examples/PerSensorMode
        pio ci --lib="." --board=${{ matrix.board }} examples/SingleIntervalMode
        pio ci --lib="." --board=${{ matrix.board }} examples/InterruptDrivenSensors
        pio ci --lib="." --board=${{ matrix.board }} examples/PerSensorWithSleep
        pio ci --lib="." --board=${{ matrix.board }} examples/SingleIntervalWifi

    - name: Run static analysis
      run: pio check --pattern="src/*.cpp" --pattern="src/*.h"
